# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.signer_pb2 as signer__pb2


class SignerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenKeypair = channel.unary_unary(
                '/signer.Signer/GenKeypair',
                request_serializer=signer__pb2.GenKeypairRequest.SerializeToString,
                response_deserializer=signer__pb2.GenKeypairResponse.FromString,
                )
        self.GetAllKeys = channel.unary_unary(
                '/signer.Signer/GetAllKeys',
                request_serializer=signer__pb2.GetAllKeysRequest.SerializeToString,
                response_deserializer=signer__pb2.GetAllKeysResponse.FromString,
                )
        self.Sign = channel.unary_unary(
                '/signer.Signer/Sign',
                request_serializer=signer__pb2.SignRequest.SerializeToString,
                response_deserializer=signer__pb2.SignResponse.FromString,
                )


class SignerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenKeypair(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenKeypair': grpc.unary_unary_rpc_method_handler(
                    servicer.GenKeypair,
                    request_deserializer=signer__pb2.GenKeypairRequest.FromString,
                    response_serializer=signer__pb2.GenKeypairResponse.SerializeToString,
            ),
            'GetAllKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllKeys,
                    request_deserializer=signer__pb2.GetAllKeysRequest.FromString,
                    response_serializer=signer__pb2.GetAllKeysResponse.SerializeToString,
            ),
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=signer__pb2.SignRequest.FromString,
                    response_serializer=signer__pb2.SignResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'signer.Signer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Signer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenKeypair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/signer.Signer/GenKeypair',
            signer__pb2.GenKeypairRequest.SerializeToString,
            signer__pb2.GenKeypairResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/signer.Signer/GetAllKeys',
            signer__pb2.GetAllKeysRequest.SerializeToString,
            signer__pb2.GetAllKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/signer.Signer/Sign',
            signer__pb2.SignRequest.SerializeToString,
            signer__pb2.SignResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
