# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csigner.proto\x12\x06signer\"\x13\n\x11GenKeypairRequest\"\'\n\x12GenKeypairResponse\x12\x11\n\tpublicKey\x18\x01 \x01(\t\"\x13\n\x11GetAllKeysRequest\"\"\n\x12GetAllKeysResponse\x12\x0c\n\x04keys\x18\x01 \x03(\t\"(\n\x0bSignRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"!\n\x0cSignResponse\x12\x11\n\tsignature\x18\x01 \x01(\t2\xc5\x01\n\x06Signer\x12\x43\n\nGenKeypair\x12\x19.signer.GenKeypairRequest\x1a\x1a.signer.GenKeypairResponse\x12\x43\n\nGetAllKeys\x12\x19.signer.GetAllKeysRequest\x1a\x1a.signer.GetAllKeysResponse\x12\x31\n\x04Sign\x12\x13.signer.SignRequest\x1a\x14.signer.SignResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GENKEYPAIRREQUEST']._serialized_start=24
  _globals['_GENKEYPAIRREQUEST']._serialized_end=43
  _globals['_GENKEYPAIRRESPONSE']._serialized_start=45
  _globals['_GENKEYPAIRRESPONSE']._serialized_end=84
  _globals['_GETALLKEYSREQUEST']._serialized_start=86
  _globals['_GETALLKEYSREQUEST']._serialized_end=105
  _globals['_GETALLKEYSRESPONSE']._serialized_start=107
  _globals['_GETALLKEYSRESPONSE']._serialized_end=141
  _globals['_SIGNREQUEST']._serialized_start=143
  _globals['_SIGNREQUEST']._serialized_end=183
  _globals['_SIGNRESPONSE']._serialized_start=185
  _globals['_SIGNRESPONSE']._serialized_end=218
  _globals['_SIGNER']._serialized_start=221
  _globals['_SIGNER']._serialized_end=418
# @@protoc_insertion_point(module_scope)
