name: Deploy Node.js app to server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@80.249.131.220 << 'EOF'
          cd solana-web3-loyalty/
          git pull
          docker-compose down
          export SOLANA_PRIVATE_KEY=${{ secrets.SOLANA_PRIVATE_KEY }}
          docker-compose up --build -d
        EOF
